# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makesky_rcpp <- function(outfile, albedo = 0.5, turbidity = 3.0, elevation = 10.0, azimuth_deg = 90, resolution = 2048L, numbercores = 1L, square_projection = FALSE, model = "hosek", prg_dataset = "", altitude = 0.0, visibility = 50.0, render_solar_disk = TRUE) {
    invisible(.Call(`_skymodelr_makesky_rcpp`, outfile, albedo, turbidity, elevation, azimuth_deg, resolution, numbercores, square_projection, model, prg_dataset, altitude, visibility, render_solar_disk))
}

calculate_raw_prague <- function(phi, theta, elevation, albedo, altitude, visibility, azimuth_deg = 90, numbercores = 1L, prg_dataset = "", render_solar_disk = TRUE) {
    .Call(`_skymodelr_calculate_raw_prague`, phi, theta, elevation, albedo, altitude, visibility, azimuth_deg, numbercores, prg_dataset, render_solar_disk)
}

make_starfield_rcpp <- function(outfile, stars, resolution = 2048L, zero_point = 1.0, lon_deg = 0.0, lat_deg = 0.0, jd = 2451545.0, turbidity = 3.0, ozone_du = 300.0, altitude = 0.0, star_width = 1.0, use_rgb = TRUE, atmosphere_effects = TRUE, upper_hemisphere_only = TRUE, numbercores = 1L, precision_multiplier = 10000) {
    invisible(.Call(`_skymodelr_make_starfield_rcpp`, outfile, stars, resolution, zero_point, lon_deg, lat_deg, jd, turbidity, ozone_du, altitude, star_width, use_rgb, atmosphere_effects, upper_hemisphere_only, numbercores, precision_multiplier))
}

