# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makesky_rcpp <- function(outfile, albedo = 0.5, turbidity = 3.0, elevation = 10.0, resolution = 2048L, numbercores = 1L, square_projection = FALSE, model = "hosek", prg_dataset = "", visibility = 50.0) {
    invisible(.Call(`_skymodelr_makesky_rcpp`, outfile, albedo, turbidity, elevation, resolution, numbercores, square_projection, model, prg_dataset, visibility))
}

